name: Feature Request
description: Suggest a new feature or enhancement
labels: enhancement

body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request

        Please provide a clear and concise description of the feature or enhancement.

  - type: textarea
    attributes:
      label: What would you like to see added or changed?
      placeholder: "Describe your feature request..."
      required: true

  - type: input
    attributes:
      label: Why is this feature important?
      placeholder: "Explain the need for this feature..."
      required: true

